package pojo;
// Generated Oct 17, 2018 2:47:48 PM by Hibernate Tools 4.3.1



/**
 * Contact generated by hbm2java
 */
public class Contact  implements java.io.Serializable {


     private Integer idContact;
     private Customer customer;
     private String phone;
     private String mobile;
     private String imo;
     private String viber;
     private String fb;

    public Contact() {
    }

	
    public Contact(Customer customer) {
        this.customer = customer;
    }
    public Contact(Customer customer, String phone, String mobile, String imo, String viber, String fb) {
       this.customer = customer;
       this.phone = phone;
       this.mobile = mobile;
       this.imo = imo;
       this.viber = viber;
       this.fb = fb;
    }
   
    public Integer getIdContact() {
        return this.idContact;
    }
    
    public void setIdContact(Integer idContact) {
        this.idContact = idContact;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getImo() {
        return this.imo;
    }
    
    public void setImo(String imo) {
        this.imo = imo;
    }
    public String getViber() {
        return this.viber;
    }
    
    public void setViber(String viber) {
        this.viber = viber;
    }
    public String getFb() {
        return this.fb;
    }
    
    public void setFb(String fb) {
        this.fb = fb;
    }




}


