package pojo;
// Generated Oct 15, 2018 12:51:14 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer idCustomer;
     private Customerstatus customerstatus;
     private String fullname;
     private String addressLine1;
     private String addressLine2;
     private String city;
     private String discription;
     private String email;
     private String pword;
     private String nic;
     private Integer gender;
     private String confirmcode;
     private Date registerDate;
     private Set<Cusupload> cusuploads = new HashSet<Cusupload>(0);
     private Set<Login> logins = new HashSet<Login>(0);
     private Set<Request> requestsForRequestTo = new HashSet<Request>(0);
     private Set<Review> reviews = new HashSet<Review>(0);
     private Set<Request> requestsForRequestFrom = new HashSet<Request>(0);
     private Set<Chat> chatsForChatTo = new HashSet<Chat>(0);
     private Set<Payment> payments = new HashSet<Payment>(0);
     private Set<Chat> chatsForChatFrom = new HashSet<Chat>(0);
     private Set<Contact> contacts = new HashSet<Contact>(0);

    public Customer() {
    }

	
    public Customer(Customerstatus customerstatus) {
        this.customerstatus = customerstatus;
    }
    public Customer(Customerstatus customerstatus, String fullname, String addressLine1, String addressLine2, String city, String discription, String email, String pword, String nic, Integer gender, String confirmcode, Date registerDate, Set<Cusupload> cusuploads, Set<Login> logins, Set<Request> requestsForRequestTo, Set<Review> reviews, Set<Request> requestsForRequestFrom, Set<Chat> chatsForChatTo, Set<Payment> payments, Set<Chat> chatsForChatFrom, Set<Contact> contacts) {
       this.customerstatus = customerstatus;
       this.fullname = fullname;
       this.addressLine1 = addressLine1;
       this.addressLine2 = addressLine2;
       this.city = city;
       this.discription = discription;
       this.email = email;
       this.pword = pword;
       this.nic = nic;
       this.gender = gender;
       this.confirmcode = confirmcode;
       this.registerDate = registerDate;
       this.cusuploads = cusuploads;
       this.logins = logins;
       this.requestsForRequestTo = requestsForRequestTo;
       this.reviews = reviews;
       this.requestsForRequestFrom = requestsForRequestFrom;
       this.chatsForChatTo = chatsForChatTo;
       this.payments = payments;
       this.chatsForChatFrom = chatsForChatFrom;
       this.contacts = contacts;
    }
   
    public Integer getIdCustomer() {
        return this.idCustomer;
    }
    
    public void setIdCustomer(Integer idCustomer) {
        this.idCustomer = idCustomer;
    }
    public Customerstatus getCustomerstatus() {
        return this.customerstatus;
    }
    
    public void setCustomerstatus(Customerstatus customerstatus) {
        this.customerstatus = customerstatus;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getDiscription() {
        return this.discription;
    }
    
    public void setDiscription(String discription) {
        this.discription = discription;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPword() {
        return this.pword;
    }
    
    public void setPword(String pword) {
        this.pword = pword;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public Integer getGender() {
        return this.gender;
    }
    
    public void setGender(Integer gender) {
        this.gender = gender;
    }
    public String getConfirmcode() {
        return this.confirmcode;
    }
    
    public void setConfirmcode(String confirmcode) {
        this.confirmcode = confirmcode;
    }
    public Date getRegisterDate() {
        return this.registerDate;
    }
    
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }
    public Set<Cusupload> getCusuploads() {
        return this.cusuploads;
    }
    
    public void setCusuploads(Set<Cusupload> cusuploads) {
        this.cusuploads = cusuploads;
    }
    public Set<Login> getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set<Login> logins) {
        this.logins = logins;
    }
    public Set<Request> getRequestsForRequestTo() {
        return this.requestsForRequestTo;
    }
    
    public void setRequestsForRequestTo(Set<Request> requestsForRequestTo) {
        this.requestsForRequestTo = requestsForRequestTo;
    }
    public Set<Review> getReviews() {
        return this.reviews;
    }
    
    public void setReviews(Set<Review> reviews) {
        this.reviews = reviews;
    }
    public Set<Request> getRequestsForRequestFrom() {
        return this.requestsForRequestFrom;
    }
    
    public void setRequestsForRequestFrom(Set<Request> requestsForRequestFrom) {
        this.requestsForRequestFrom = requestsForRequestFrom;
    }
    public Set<Chat> getChatsForChatTo() {
        return this.chatsForChatTo;
    }
    
    public void setChatsForChatTo(Set<Chat> chatsForChatTo) {
        this.chatsForChatTo = chatsForChatTo;
    }
    public Set<Payment> getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set<Payment> payments) {
        this.payments = payments;
    }
    public Set<Chat> getChatsForChatFrom() {
        return this.chatsForChatFrom;
    }
    
    public void setChatsForChatFrom(Set<Chat> chatsForChatFrom) {
        this.chatsForChatFrom = chatsForChatFrom;
    }
    public Set<Contact> getContacts() {
        return this.contacts;
    }
    
    public void setContacts(Set<Contact> contacts) {
        this.contacts = contacts;
    }




}


