package pojo;
// Generated Oct 17, 2018 2:47:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Customerstatus generated by hbm2java
 */
public class Customerstatus  implements java.io.Serializable {


     private Integer idCustomerStatus;
     private String cusStatusName;
     private Set<Customer> customers = new HashSet<Customer>(0);

    public Customerstatus() {
    }

    public Customerstatus(String cusStatusName, Set<Customer> customers) {
       this.cusStatusName = cusStatusName;
       this.customers = customers;
    }
   
    public Integer getIdCustomerStatus() {
        return this.idCustomerStatus;
    }
    
    public void setIdCustomerStatus(Integer idCustomerStatus) {
        this.idCustomerStatus = idCustomerStatus;
    }
    public String getCusStatusName() {
        return this.cusStatusName;
    }
    
    public void setCusStatusName(String cusStatusName) {
        this.cusStatusName = cusStatusName;
    }
    public Set<Customer> getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set<Customer> customers) {
        this.customers = customers;
    }




}


