package pojo;
// Generated Oct 15, 2018 12:51:14 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private Integer idLogin;
     private Customer customer;
     private Date intime;
     private Date outTime;
     private Integer status;

    public Login() {
    }

	
    public Login(Customer customer) {
        this.customer = customer;
    }
    public Login(Customer customer, Date intime, Date outTime, Integer status) {
       this.customer = customer;
       this.intime = intime;
       this.outTime = outTime;
       this.status = status;
    }
   
    public Integer getIdLogin() {
        return this.idLogin;
    }
    
    public void setIdLogin(Integer idLogin) {
        this.idLogin = idLogin;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Date getIntime() {
        return this.intime;
    }
    
    public void setIntime(Date intime) {
        this.intime = intime;
    }
    public Date getOutTime() {
        return this.outTime;
    }
    
    public void setOutTime(Date outTime) {
        this.outTime = outTime;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


