package pojo;
// Generated Oct 15, 2018 12:51:14 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Payment generated by hbm2java
 */
public class Payment  implements java.io.Serializable {


     private Integer idPayment;
     private Customer customer;
     private Paytype paytype;
     private Date payDate;
     private Double payValue;
     private Integer payStatus;
     private String discription;
     private String paymentcol;

    public Payment() {
    }

	
    public Payment(Customer customer, Paytype paytype) {
        this.customer = customer;
        this.paytype = paytype;
    }
    public Payment(Customer customer, Paytype paytype, Date payDate, Double payValue, Integer payStatus, String discription, String paymentcol) {
       this.customer = customer;
       this.paytype = paytype;
       this.payDate = payDate;
       this.payValue = payValue;
       this.payStatus = payStatus;
       this.discription = discription;
       this.paymentcol = paymentcol;
    }
   
    public Integer getIdPayment() {
        return this.idPayment;
    }
    
    public void setIdPayment(Integer idPayment) {
        this.idPayment = idPayment;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Paytype getPaytype() {
        return this.paytype;
    }
    
    public void setPaytype(Paytype paytype) {
        this.paytype = paytype;
    }
    public Date getPayDate() {
        return this.payDate;
    }
    
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }
    public Double getPayValue() {
        return this.payValue;
    }
    
    public void setPayValue(Double payValue) {
        this.payValue = payValue;
    }
    public Integer getPayStatus() {
        return this.payStatus;
    }
    
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }
    public String getDiscription() {
        return this.discription;
    }
    
    public void setDiscription(String discription) {
        this.discription = discription;
    }
    public String getPaymentcol() {
        return this.paymentcol;
    }
    
    public void setPaymentcol(String paymentcol) {
        this.paymentcol = paymentcol;
    }




}


