package pojo;
// Generated Oct 17, 2018 2:47:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Paytype generated by hbm2java
 */
public class Paytype  implements java.io.Serializable {


     private Integer idPayType;
     private String typeName;
     private String payTypeStatus;
     private Set<Payment> payments = new HashSet<Payment>(0);

    public Paytype() {
    }

    public Paytype(String typeName, String payTypeStatus, Set<Payment> payments) {
       this.typeName = typeName;
       this.payTypeStatus = payTypeStatus;
       this.payments = payments;
    }
   
    public Integer getIdPayType() {
        return this.idPayType;
    }
    
    public void setIdPayType(Integer idPayType) {
        this.idPayType = idPayType;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    public String getPayTypeStatus() {
        return this.payTypeStatus;
    }
    
    public void setPayTypeStatus(String payTypeStatus) {
        this.payTypeStatus = payTypeStatus;
    }
    public Set<Payment> getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set<Payment> payments) {
        this.payments = payments;
    }




}


