package pojo;
// Generated Oct 15, 2018 12:51:14 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Request generated by hbm2java
 */
public class Request  implements java.io.Serializable {


     private Integer idRequest;
     private Customer customerByRequestTo;
     private Customer customerByRequestFrom;
     private Integer conferm;
     private Date confermDateTime;
     private Date requestDateTime;
     private Set<Chat> chats = new HashSet<Chat>(0);

    public Request() {
    }

	
    public Request(Customer customerByRequestTo, Customer customerByRequestFrom) {
        this.customerByRequestTo = customerByRequestTo;
        this.customerByRequestFrom = customerByRequestFrom;
    }
    public Request(Customer customerByRequestTo, Customer customerByRequestFrom, Integer conferm, Date confermDateTime, Date requestDateTime, Set<Chat> chats) {
       this.customerByRequestTo = customerByRequestTo;
       this.customerByRequestFrom = customerByRequestFrom;
       this.conferm = conferm;
       this.confermDateTime = confermDateTime;
       this.requestDateTime = requestDateTime;
       this.chats = chats;
    }
   
    public Integer getIdRequest() {
        return this.idRequest;
    }
    
    public void setIdRequest(Integer idRequest) {
        this.idRequest = idRequest;
    }
    public Customer getCustomerByRequestTo() {
        return this.customerByRequestTo;
    }
    
    public void setCustomerByRequestTo(Customer customerByRequestTo) {
        this.customerByRequestTo = customerByRequestTo;
    }
    public Customer getCustomerByRequestFrom() {
        return this.customerByRequestFrom;
    }
    
    public void setCustomerByRequestFrom(Customer customerByRequestFrom) {
        this.customerByRequestFrom = customerByRequestFrom;
    }
    public Integer getConferm() {
        return this.conferm;
    }
    
    public void setConferm(Integer conferm) {
        this.conferm = conferm;
    }
    public Date getConfermDateTime() {
        return this.confermDateTime;
    }
    
    public void setConfermDateTime(Date confermDateTime) {
        this.confermDateTime = confermDateTime;
    }
    public Date getRequestDateTime() {
        return this.requestDateTime;
    }
    
    public void setRequestDateTime(Date requestDateTime) {
        this.requestDateTime = requestDateTime;
    }
    public Set<Chat> getChats() {
        return this.chats;
    }
    
    public void setChats(Set<Chat> chats) {
        this.chats = chats;
    }




}


