package pojo;
// Generated Oct 17, 2018 2:47:48 PM by Hibernate Tools 4.3.1



/**
 * Subscribe generated by hbm2java
 */
public class Subscribe  implements java.io.Serializable {


     private Integer idSubs;
     private String email;

    public Subscribe() {
    }

    public Subscribe(String email) {
       this.email = email;
    }
   
    public Integer getIdSubs() {
        return this.idSubs;
    }
    
    public void setIdSubs(Integer idSubs) {
        this.idSubs = idSubs;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


